### ISSUE TITLE
iOS実機でバックグラウンド処理が実行されているかを確認する(?pt)

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/The4thDay-of-MikkaBozu#104]
# 現状
一度[現在の状況](https://github.com/cammelworks/The4thDay-of-MikkaBozu/tree/784a6d64654341d41fddd6963798e0fe6f4472f3)でiOS実機ビルドをおこない、バックグランドで現在位置を取得し、移動距離が更新されるかを確認する。

# タスク

## 7/4
@kugimasa
- [x]  iOS実機へのビルド
- [x] ~記録画面で**START**を押しアプリをバックグラウンドにした状態で歩く
       その後、移動距離が変化するか確認する~
> 現在調査中 📝 
> >ダメでした 😢

@iHiromu 
- [x]  iOS実機へのビルド
- [x] ~記録画面で**START**を押しアプリをバックグラウンドにした状態で歩く
       その後、移動距離が変化するか確認する~

@TakedaHiroki 
- [ ] XCode、TARGET->Runner->Signing & CapabilitiesからCammelのDeveloperアカウントにサインインする
      (6桁の認証コードが必要になるので、タスクに着手する際に@kugimasaにメンションを飛ばしてください)

---
## 7/11

- [x] FlutterでSwiftのネイティブコードを実行する

- [ ] バックグランドで位置情報から距離を計算する

**Comment by kugimasa** [comment]
@iHiromu 
AndroidStudioで以下のコマンドを実行した後に実機に繋いでビルドするとうまくいくかもです

```sh
flutter clean
cd ios
rm Pods
```

**Comment by iHiromu** [comment]
両方試してみたんだけどうまく入れられなかった
flutter cleanのやつはこれはうまくできてないってことなのかな？
![image](https://user-images.githubusercontent.com/46994075/86516736-182c9680-be5e-11ea-848a-d21760f33121.png)
![image](https://user-images.githubusercontent.com/46994075/86516825-b4569d80-be5e-11ea-8538-13ba41287eea.png)

**Comment by kugimasa** [comment]
現状では実機で動いていないようです

**Comment by kugimasa** [comment]
# setStateの場所を変更してみる
https://github.com/cammelworks/The4thDay-of-MikkaBozu/blob/4a9ee5f057c8968f4b36314320cac86439238970/lib/Pages/MeasurementPage/measurement_page.dart#L27-L30

`measurement_pannel.dart`の方に`setState()`を持ってくる？？

**Comment by kugimasa** [comment]
# FlutterからSwiftのネイティブコードを呼び出す
https://qiita.com/zQmjRAb73seN5RM/items/af21e05341bbae79d434

**Comment by iHiromu** [comment]
上の参考サイトでswiftの方に少し誤りあるのでこっちを使ってください

import UIKit
import Flutter

@UIApplicationMain
@objc class AppDelegate: FlutterAppDelegate {
  override func application(
    _ application: UIApplication,
    didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?
  ) -> Bool {
    Timer.scheduledTimer(timeInterval: 10, target: self, selector: #selector(AppDelegate.timer), userInfo: nil, repeats: false)

    GeneratedPluginRegistrant.register(with: self)
    return super.application(application, didFinishLaunchingWithOptions: launchOptions)
  }

  @objc func timer() {
    let controller : FlutterViewController = window?.rootViewController as! FlutterViewController
    let channel = FlutterMethodChannel(name: "ChannelName", binaryMessenger: controller as! FlutterBinaryMessenger)
    DispatchQueue.main.async {
      channel.invokeMethod("methodName", arguments: "Swift からのメッセージ")
    }
  }
}

**Comment by kugimasa** [comment]
DONE:+1:
距離計算は #86 で
