### ISSUE TITLE
サインイン処理後に画面をスライドするとアカウント処理前のページに戻ってしまう

### ISSUE THREAD

**Issue by kugimasa** [cammelworks/The4thDay-of-MikkaBozu#114]
**バグ概要🐛**
サインイン後にスッとスライドバーを出す感覚で画面を左から右にスライドさせると
サインインしていたはずが、されずに前のページにに戻ってしまいます。

サインインだけじゃなくて、ユーザ登録でも同じかも!!!

**Commit-Id** : a8d97277b824648cdd4b965d8fd64373de9b4bfb
PR #109 時点

**類似Issue**
#110 

**再現するには?**
バグを再現するためのステップを記載
1. サインインボタンを押しサインイン
2. ログイン後の画面に遷移
3. サイドバーを出す感覚で画面左から右へスライド
4. メール入力画面に戻る

**どうなって欲かった？**
サインインしたら戻らないで欲しい

**実行環境**
 - Device: Cammel-ios (iPhone6s)
 - OS: iOS 13.3

**Comment by Yamakatsu63** [comment]
SignoutButtonでやっているように`Navigator.pushAndRemoveUntil()`を使うと実装できそう。
