### ISSUE TITLE
チーム検索/作成ページから戻るときにエラーが映る

### ISSUE THREAD

**Issue by NishidaYujiro** [cammelworks/The4thDay-of-MikkaBozu#122]
**バグ概要🐛**
チーム検索ページまたはチーム作成ページでキーボードを出した状態で戻るボタンを押すとBottom overflowed（おそらく）のエラーが一瞬表示される

**Commit-Id** 9a67d5192bb1904dbfca8fcbf864c6b527be0c89

**再現するには?**
バグを再現するためのステップを記載
1.  チーム作成ページ（チーム検索ページ）へ遷移
2.  戻るボタン をクリック
3. エラーが表示される

**どうなって欲かった？**
エラーが表示されず前の画面に戻れる

**実行環境**
 - Device: [Pixel 2 API 29]
 - OS: [Android 10.0]

**Comment by iHiromu** [comment]
実機(iOS)に落として確認したところエラーは映りませんでした。

**Comment by Yamakatsu63** [comment]
チーム検索ページと作成ページへの遷移を変えたので解決しました。
