### ISSUE TITLE
カレンダーで走った距離をグラデーションで表示する

### ISSUE THREAD

**Issue by Yamakatsu63** [cammelworks/The4thDay-of-MikkaBozu#148]
# 概要
カレンダーで走った距離をグラデーションで表示する際の
カラーコードを決めてほしいです。
RGBでもHSVでも大丈夫です。

**Comment by daigo0907** [comment]
### GitHubの草はこんな感じでした（カラーピッカーで取得した）
![image](https://user-images.githubusercontent.com/40502921/101729627-d9c99080-3afb-11eb-9816-bf6bd114a413.png)

### HSBでS（彩度）のみを下げていくとこんな感じ（H=198,S=15,35,55,75,95,V=80）
![image](https://user-images.githubusercontent.com/40502921/101734505-b9053900-3b03-11eb-9ef4-07f390a11e96.png)

**Comment by daigo0907** [comment]
## これでお願いします
彩度のみを下げると色の変化がはっきりしないので、
GitHubの草のHSBをベースにHをいじりました

![image](https://user-images.githubusercontent.com/40502921/101737165-da682400-3b07-11eb-9c17-8888255e2257.png)

https://coolors.co/ebedf0-9bd1e8-419dc4-307fa1-21576e

**Comment by Yamakatsu63** [comment]
こんな感じになりました。
![2020-12-11](https://user-images.githubusercontent.com/40345570/101882965-f1774680-3bd9-11eb-8cb8-aaaba1f4820c.png)

**Comment by daigo0907** [comment]
確認しました！
