### ISSUE TITLE
ユーザーアイコンを追加できる

### ISSUE THREAD

**Issue by tyanio** [cammelworks/The4thDay-of-MikkaBozu#169]
# 概要
ユーザー名以外にもユーザーを視覚的に認識するためにはユーザーのアイコンを導入するのは大事だと思われます！
チャットでは特に文字情報をチャット以外に追加したくないのもあり早急に導入していただきたい！

## 要調査！
- スマホのローカルアクセスするときにimage_pickerだとエラーが出てしまう！代替手段or解決手段は要調査！
- 切り抜き加工or切り抜き表示or最小の正方形で切り抜いて丸形表示
- その手段

## 詳細なTODO
- [x] Sidemenuにアップロードボタンを追加する
- [x] スマホのローカルストレージにアクセスする
  - [x] Android API 28 以下
  - [x] Android API 29 以上
  - [x] iOS
- [x] 切り抜き加工をする
- [x] Firebase Storageにアイコンをアップロードする
- [x] Firebase StorageのデータとFirestoreのユーザー情報とを紐づける
- [x] 各ページに表示する
  - [x] sidemenu
  - [x] team_page
  - [x] chat_page

```
モック画像
```

**Comment by tyanio** [comment]
## image_picker
https://makulogsleep.com/flutter-image-store

**Comment by Yamakatsu63** [comment]
# Image Cropper
https://pub.dev/packages/image_cropper
