### ISSUE TITLE
チャットが来たらプッシュ通知が来る

### ISSUE THREAD

**Issue by tyanio** [cammelworks/The4thDay-of-MikkaBozu#193]
# 概要
現在チャットページを確認しないとチャットが来たかどうかも分からないのでプッシュ通知が来るようにしてほしいです。
そのうえでプッシュ通知がミュートをユーザーが設定できるようにしてほしいです。

## 詳細なTODO
- [x] 通知許可のダイアログを表示する
  - [x] iOS
- [x] Firebase Cloud Messaging(FCM)をインポートしてユーザーのトークンをデータベースに保存する
  - [x] ユーザー登録時
  - [x] ~~既存ユーザーのトークンをデータベースに保存するプログラムを一回実行する~~
  - [x] ユーザーのトークン情報がない場合にトークンをプッシュするようにする
  - [x] user一人に対して複数端末のトークンを保持できるようにする
- [x] Firebase Cloud Messaging(FCM)でコンソールからプッシュ通知ができることを確認する(print()等で確認する)
  - [x] iOS
  - [x] Android
- [x] 通知を表示する
    - [x] Foreground
      - [x] プッシュ通知が来たときに音を鳴らす
      - [x] 各アイコンに赤ぽちつける
      - [x] 該当するチャットページを見たときに赤ぽちを消す
      - ~~任意のページにいるときにチャットが飛んできたときに赤ぽちを付けることは現状不可能です~~
        - 別のIssueでやります
  - [x] Background
    - [x] ~~iOS~~
    - [x] Android
- [x] Functionsでデータベース監視してチャットが更新されたタイミングでメッセージを特定のユーザーに送信する
  - [x] Cloud FireStoreのデータを取ってくる
  - [x] Cloud FireStoreに新しく追加されたデータを取ってくる
  - [x] Cloud FireStoreに新しくデータが追加されたときに受信メンバーのトークンを取ってくる
  - [x] Cloud FireStoreに新しくデータが追加されたときにメッセージを送信する
```
モック画像
```

**Comment by Yamakatsu63** [comment]
参考サイト
https://qiita.com/yana1316/items/9bd3806efc9cbdddcba9
