### ISSUE TITLE
他のメンバーの記録を見る(13pt)

### ISSUE THREAD

**Issue by NishidaYujiro** [cammelworks/The4thDay-of-MikkaBozu#20]
# 概要
チームのほかのメンバーがどれぐらい走ったかを確認できるようにしたい

## 詳細なTODO

モック画像

![ほかのメンバーの記録を見る (1)](https://user-images.githubusercontent.com/40502921/86560001-4adaaa00-bf98-11ea-960b-cb31c0986002.png)

**Comment by kugimasa** [comment]
- 自分の情報はMYPAGEから
