### ISSUE TITLE
走った距離が入力できる(3pt)

### ISSUE THREAD

**Issue by iHiromu** [cammelworks/The4thDay-of-MikkaBozu#21]
# 概要

## 詳細なTODO

- [x] 走った距離の入力フォームの作成

- [x] firebase内に入力データを保存する

- [x] データーベースの変更
   - 一意ドキュメントID -> (email , team_name)　に変更

- [x] 保存したデータを出力する

```
モック画像
```

![DataStructure-Page-1 (1)](https://user-images.githubusercontent.com/40158101/84364670-5c37cd00-ac0b-11ea-9dab-351490ba5e85.png)

![DataStructure-Page-2](https://user-images.githubusercontent.com/40158101/84364678-5e9a2700-ac0b-11ea-8e4c-007a16e2e520.png)

**Comment by Yamakatsu63** [comment]
チーム名やメールアドレスは一意になってるのでそれらをDocumentIDとします。
こっちのほうが検索が楽になります。
