### ISSUE TITLE
iOSでexceptionが発生した場合フリーズするバグ

### ISSUE THREAD

**Issue by iHiromu** [cammelworks/The4thDay-of-MikkaBozu#42]
![image](https://user-images.githubusercontent.com/46994075/82666450-ef1ac280-9c70-11ea-895d-ad660a158856.png)

- 登録するときに既に使われているアドレスだった場合

- パスワードを間違え場合

現在確認されている上２つが起こった場合、画像のようにexceptionが出てフリーズします．

***

## 確認お願いします

- [ ] @kugimasa 

- [ ] @TakedaHiroki

**Comment by tyanio** [comment]
下の画像の青丸のところをクリックすると真ん中のウィンドウが出てくるので、そのウィンドウの左のチェックのところを見てほしい
![2020-05-22 (5)_LI](https://user-images.githubusercontent.com/19584781/82673101-46726000-9c7c-11ea-9254-e648df73d0c5.jpg)

**Comment by tyanio** [comment]
# 原因分かりました
Debugモードの、上のコメント画像を参考にすると真ん中のウインドウの左のメニューのチェックを付けると例外が出る際にブレークポイントを作ってスレッドを停止してしまうようです
青丸の上の再生ボタンみたいなやつでスレッドを動かすことができるのでそこを活用して例外対策していきましょう！
ちなみにこれを外すとフリーズすることはなくなりますが、デバッグモードの意味がなくなるので非推奨です
