### ISSUE TITLE
サインインした後、もとのサインインの画面に戻されます

### ISSUE THREAD

**Issue by daigo0907** [cammelworks/The4thDay-of-MikkaBozu#45]
本来は、サインイン後には、アカウント登録ありの画面に飛ぶはずが、飛ばない。。。
もともとのサインインの画面に戻ります

おそらく自分の環境が怪しいと思うんですが、、、

*** 
ログを見ていると、
E/FirebaseInstanceId(11608): binding to the service failed
とエラー出てました

***

## 解決
#44 に載ってる通りです
flutterのバージョンの違いでした
確認不足でした。。。

**Comment by tyanio** [comment]
現状自分の環境では動いてるのでエラーのほうからチェックしていってます
